server:
  port: 8080
  servlet:
    context-path: /blog

spring:
  application:
    name: blog
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/myblog
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: ERROR
    org.springframework.data: DEBUG
  file:
    name: logs/blog.log